### PR TITLE
fix: classification of pci and usb devices

### LINKED ISSUE #136: Put all "unknown" devices that are connected via USB into "usb" instead of "unknown"
That's more intuitive. Currently I have write modules to look both in unknown and usb.

https://github.com/Mic92/dotfiles/blob/b8db102dab16013d48af91bb674ccd1160444e0f/machines/turingmachine/facter.json#L3929

### PR DESCRIPTION
**Pull request by brianmcgee**
Improves overall classification by capturing the class list of the underlying hardware item.

When the overall hardware class is unknown, we call back to the class list which typically identifies it as usb or pci etc.

Adds the `class` and `class_list` fields to the JSON output for clarity.

We should consider whether we allow the same hardware item in different sections of the hardware report based on the `class_list`.

Closes #136

### CODE REVIEW

File: pkg/hwinfo/hardware.go [hunk 1]
```diff
@@ -263,7 +263,10 @@ const (
 // HardwareDevice represents a hardware component detected in the system.
 type HardwareDevice struct {
 	// Class represents the type of the hardware component.
-	Class HardwareClass `json:"-"`
+	Class HardwareClass `json:"class,omitempty"`
```
Comment (Mic92) [inline pkg/hwinfo/hardware.go:266]: After scrolling through the report, this actually doesn't add much and seems redundant.
The class_list is fine though.

```suggestion
	Class HardwareClass `json:"-"`
```

**Comment by Mic92** [comment]
Looks overall good to me. Tested on my framework, where I only have one non-classified device left.

File: pkg/hwinfo/hardware.go (hunk 1 above)
Comment (brianmcgee) [reply pkg/hwinfo/hardware.go:266]: The class is implied by the section the device is placed in, and if it's unknown we look to the first entry in the class list, so I'm happy removing it from the json output
